### ISSUE TITLE
can this collection ensure FIFO?

### ISSUE THREAD

**Issue by HaoLiuHust** [CodeExMachina/BlockingCollection#2]

**Comment by gm127** [comment]
Yes. BlockingCollection synchronizes access to a std::deque. So as long as it is configured to use the Queue collection type (e.g. BlockingQueue) then all takes will go to std::deque's pop_front method. This ensures FIFO.

**Comment by HaoLiuHust** [comment]
Thanks for your reply, I have already use it, wonderful work
